In [28]:
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pandas as pd
import pickle

In [29]:
data = pd.read_csv("/Users/abhijitdash/Downloads/Bank-data-churn-model.csv")
data.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [30]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [31]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [32]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [33]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [34]:
 #Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [35]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [36]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [40]:

##load the encoder and scaler
with open('gender_label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('oneHotEncoder_value.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

##ANN Regression problem Statement

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [44]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression, not applying activation function so default linear activation (only for regression)
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae']) ### for regression use MAE

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [45]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [48]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True) ## validation loss(important)

In [49]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100

2026-03-14 13:16:36.416723: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

250/250 [==============================] - 3s 4ms/step - loss: 100422.9922 - mae: 100422.9922 - val_loss: 98691.8828 - val_mae: 98691.8828
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 100288.7031 - mae: 100288.7031 - val_loss: 98405.4688 - val_mae: 98405.4688
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 99787.6094 - mae: 99787.6094 - val_loss: 97656.7891 - val_mae: 97656.7891
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 98793.3438 - mae: 98793.3438 - val_loss: 96383.7188 - val_mae: 96383.7188
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 97323.1172 - mae: 97323.1172 - val_loss: 94668.7031 - val_mae: 94668.7031
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 95546.7891 - mae: 95546.7891 - val_loss: 92741.8750 - val_mae: 92741.8750
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 93691.1328 - mae: 93691.1328 - val_loss: 91105.6016 - val_mae: 91105.6016
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 92117.0703 - mae: 92117.0703 - val_loss: 89936.1250 - val_mae: 89936.1250
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 91006.6172 - mae: 91006.6172 - val_loss: 89125.0234 - val_mae: 89125.0234
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 90176.1250 - mae: 90176.1250 - val_loss: 88482.0156 - val_mae: 88482.0156
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 89504.6016 - mae: 89504.6016 - val_loss: 87843.9922 - val_mae: 87843.9922
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 88735.1406 - mae: 88735.1406 - val_loss: 87057.6562 - val_mae: 87057.6562
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 87896.8438 - mae: 87896.8438 - val_loss: 86109.5859 - val_mae: 86109.5859
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 86839.2344 - mae: 86839.2344 - val_loss: 84956.5312 - val_mae: 84956.5312
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 85665.1719 - mae: 85665.1719 - val_loss: 83690.6562 - val_mae: 83690.6562
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 84374.5312 - mae: 84374.5312 - val_loss: 82311.3984 - val_mae: 82311.3984
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 82937.0000 - mae: 82937.0000 - val_loss: 80840.8281 - val_mae: 80840.8281
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 81474.5938 - mae: 81474.5938 - val_loss: 79288.3984 - val_mae: 79288.3984
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 79870.5391 - mae: 79870.5391 - val_loss: 77661.3984 - val_mae: 77661.3984
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 78191.8438 - mae: 78191.8438 - val_loss: 75986.0000 - val_mae: 75986.0000
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 76592.9062 - mae: 76592.9062 - val_loss: 74273.8047 - val_mae: 74273.8047
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 74937.4219 - mae: 74937.4219 - val_loss: 72601.4844 - val_mae: 72601.4844
Epoch 23/100
250/250 [==============================] - 1s 4ms/step - loss: 73300.0234 - mae: 73300.0234 - val_loss: 70938.6797 - val_mae: 70938.6797
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 71630.3672 - mae: 71630.3672 - val_loss: 69331.4453 - val_mae: 69331.4453
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 70031.6484 - mae: 70031.6484 - val_loss: 67774.1875 - val_mae: 67774.1875
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 68442.6094 - mae: 68442.6094 - val_loss: 66255.2422 - val_mae: 66255.2422
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 66952.8125 - mae: 66952.8125 - val_loss: 64844.8086 - val_mae: 64844.8086
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 65523.8633 - mae: 65523.8633 - val_loss: 63531.9062 - val_mae: 63531.9062
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 64165.6836 - mae: 64165.6836 - val_loss: 62218.1680 - val_mae: 62218.1680
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 62838.7227 - mae: 62838.7227 - val_loss: 60995.3125 - val_mae: 60995.3125
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 61586.1953 - mae: 61586.1953 - val_loss: 59832.3594 - val_mae: 59832.3594
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 60381.9141 - mae: 60381.9141 - val_loss: 58735.3672 - val_mae: 58735.3672
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 59233.1094 - mae: 59233.1094 - val_loss: 57727.1484 - val_mae: 57727.1484
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 58199.2930 - mae: 58199.2930 - val_loss: 56794.5898 - val_mae: 56794.5898
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 57203.6719 - mae: 57203.6719 - val_loss: 55928.0625 - val_mae: 55928.0625
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 56301.3164 - mae: 56301.3164 - val_loss: 55113.1797 - val_mae: 55113.1797
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 55432.0508 - mae: 55432.0508 - val_loss: 54405.6758 - val_mae: 54405.6758
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 54641.9766 - mae: 54641.9766 - val_loss: 53745.6719 - val_mae: 53745.6719
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 53931.5938 - mae: 53931.5938 - val_loss: 53161.0000 - val_mae: 53161.0000
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 53305.3984 - mae: 53305.3984 - val_loss: 52636.9102 - val_mae: 52636.9102
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 52719.7188 - mae: 52719.7188 - val_loss: 52184.4961 - val_mae: 52184.4961
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 52210.8984 - mae: 52210.8984 - val_loss: 51764.7227 - val_mae: 51764.7227
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 51772.5391 - mae: 51772.5391 - val_loss: 51415.9727 - val_mae: 51415.9727
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 51382.4727 - mae: 51382.4727 - val_loss: 51136.8359 - val_mae: 51136.8359
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 51044.5039 - mae: 51044.5039 - val_loss: 50917.6523 - val_mae: 50917.6523
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 50764.6562 - mae: 50764.6562 - val_loss: 50728.6836 - val_mae: 50728.6836
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 50539.1953 - mae: 50539.1953 - val_loss: 50577.4453 - val_mae: 50577.4453
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 50351.0039 - mae: 50351.0039 - val_loss: 50466.0664 - val_mae: 50466.0664
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 50195.2812 - mae: 50195.2812 - val_loss: 50352.5117 - val_mae: 50352.5117
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 50062.5859 - mae: 50062.5859 - val_loss: 50298.6055 - val_mae: 50298.6055
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49956.7422 - mae: 49956.7422 - val_loss: 50209.4922 - val_mae: 50209.4922
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49894.4609 - mae: 49894.4609 - val_loss: 50161.9570 - val_mae: 50161.9570
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49831.3203 - mae: 49831.3203 - val_loss: 50124.3594 - val_mae: 50124.3594
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49796.0234 - mae: 49796.0234 - val_loss: 50099.0156 - val_mae: 50099.0156
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49758.5156 - mae: 49758.5156 - val_loss: 50074.9023 - val_mae: 50074.9023
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49730.8594 - mae: 49730.8594 - val_loss: 50068.1367 - val_mae: 50068.1367
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 49694.7227 - mae: 49694.7227 - val_loss: 50043.4805 - val_mae: 50043.4805
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49681.1133 - mae: 49681.1133 - val_loss: 50059.1914 - val_mae: 50059.1914
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 49665.6719 - mae: 49665.6719 - val_loss: 50025.2773 - val_mae: 50025.2773
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 49644.3125 - mae: 49644.3125 - val_loss: 50027.3828 - val_mae: 50027.3828
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 49636.0977 - mae: 49636.0977 - val_loss: 50045.0898 - val_mae: 50045.0898
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 49630.7969 - mae: 49630.7969 - val_loss: 50014.2109 - val_mae: 50014.2109
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 49618.7969 - mae: 49618.7969 - val_loss: 50009.8906 - val_mae: 50009.8906
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49618.5078 - mae: 49618.5078 - val_loss: 50016.3047 - val_mae: 50016.3047
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 49613.5938 - mae: 49613.5938 - val_loss: 50008.2734 - val_mae: 50008.2734
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 49598.0938 - mae: 49598.0938 - val_loss: 50036.1680 - val_mae: 50036.1680
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 49605.6680 - mae: 49605.6680 - val_loss: 50020.6094 - val_mae: 50020.6094
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 49598.5703 - mae: 49598.5703 - val_loss: 50002.4688 - val_mae: 50002.4688
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 49593.2695 - mae: 49593.2695 - val_loss: 50005.5273 - val_mae: 50005.5273
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 49597.3477 - mae: 49597.3477 - val_loss: 49996.7656 - val_mae: 49996.7656
Epoch 71/100
250/250 [==============================] - 1s 3ms/step - loss: 49590.8359 - mae: 49590.8359 - val_loss: 49993.8242 - val_mae: 49993.8242
Epoch 72/100
250/250 [==============================] - 1s 3ms/step - loss: 49595.6797 - mae: 49595.6797 - val_loss: 49994.8789 - val_mae: 49994.8789
Epoch 73/100
250/250 [==============================] - 1s 4ms/step - loss: 49593.0391 - mae: 49593.0391 - val_loss: 49996.7695 - val_mae: 49996.7695
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 49583.1289 - mae: 49583.1289 - val_loss: 49992.0000 - val_mae: 49992.0000
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 49584.1133 - mae: 49584.1133 - val_loss: 49991.8398 - val_mae: 49991.8398
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 49588.8359 - mae: 49588.8359 - val_loss: 49991.6641 - val_mae: 49991.6641
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 49584.4570 - mae: 49584.4570 - val_loss: 49988.6992 - val_mae: 49988.6992
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 49577.1133 - mae: 49577.1133 - val_loss: 49991.1445 - val_mae: 49991.1445
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 49578.5195 - mae: 49578.5195 - val_loss: 49983.2227 - val_mae: 49983.2227
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 49579.3867 - mae: 49579.3867 - val_loss: 49989.2266 - val_mae: 49989.2266
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 49581.6250 - mae: 49581.6250 - val_loss: 49978.4141 - val_mae: 49978.4141
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 49583.6250 - mae: 49583.6250 - val_loss: 49984.3438 - val_mae: 49984.3438
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 49578.6680 - mae: 49578.6680 - val_loss: 49998.4648 - val_mae: 49998.4648
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 49577.7148 - mae: 49577.7148 - val_loss: 49975.5352 - val_mae: 49975.5352
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 49563.1367 - mae: 49563.1367 - val_loss: 49994.2031 - val_mae: 49994.2031
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 49583.1016 - mae: 49583.1016 - val_loss: 49978.7344 - val_mae: 49978.7344
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 49584.7539 - mae: 49584.7539 - val_loss: 49976.4570 - val_mae: 49976.4570
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 49592.7891 - mae: 49592.7891 - val_loss: 49967.6445 - val_mae: 49967.6445
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 49591.5586 - mae: 49591.5586 - val_loss: 49976.8594 - val_mae: 49976.8594
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 49577.7969 - mae: 49577.7969 - val_loss: 49969.4766 - val_mae: 49969.4766
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 49570.1250 - mae: 49570.1250 - val_loss: 49967.0508 - val_mae: 49967.0508
Epoch 92/100
250/250 [==============================] - 1s 3ms/step - loss: 49575.8359 - mae: 49575.8359 - val_loss: 49958.7305 - val_mae: 49958.7305
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 49564.5000 - mae: 49564.5000 - val_loss: 49989.9766 - val_mae: 49989.9766
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 49575.1953 - mae: 49575.1953 - val_loss: 49960.9922 - val_mae: 49960.9922
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 49567.7891 - mae: 49567.7891 - val_loss: 49954.5625 - val_mae: 49954.5625
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 49566.4922 - mae: 49566.4922 - val_loss: 49970.0312 - val_mae: 49970.0312
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 49579.5117 - mae: 49579.5117 - val_loss: 49947.2109 - val_mae: 49947.2109
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 49577.1094 - mae: 49577.1094 - val_loss: 49952.9883 - val_mae: 49952.9883
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 49570.4727 - mae: 49570.4727 - val_loss: 49953.8828 - val_mae: 49953.8828
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 49564.3320 - mae: 49564.3320 - val_loss: 49956.9883 - val_mae: 49956.9883

In [50]:
%load_ext tensorboard

In [53]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6008 (pid 38869), started 0:00:19 ago. (Use '!kill 38869' to kill it.)

In [54]:
##Evaluate the model on test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 49956.9883 - mae: 49956.9883
Test MAE : 49956.98828125

In [55]:
model.save('regression_model.h5')

/Users/abhijitdash/Library/CloudStorage/OneDrive-FICO/Documents/AI Bootcamp/fintech-bank-customer-churn-prediction-ann-webapp/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(